POST http://localhost:3000/api/productos HTTP/1.1
Content-Type: application/json

{
    "name": "Surtido Bagley 2",
    "description": "Galletitas",
    "price": 500,
    "stock": 10
}

###

GET http://localhost:3000/api/productos

###

DELETE http://localhost:3000/api/productos/649b30c6d09b559f8e71346f

###

GET http://localhost:3000/api/productos/649b30bed09b559f8e713469

###

PUT http://localhost:3000/api/productos/649b30bed09b559f8e713469
Content-Type: application/json

{
    "name": "Surtido Bagley 85",
    "description": "Galletitas dulces",
    "price": 10,
    "stock": 20
}
